[project]
name = "mcp-server-pox"
version = "0.1.0"
description = "A sample POX MCP server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp>=1.5.0",
    "requests>=2.32.3",
]

[dependency-groups]
lint = [
    "ruff>=0.11.2",
]
